### ISSUE TITLE
invalid invocation of hook_islandora_derivative_alter

### ISSUE THREAD

**Issue by patdunlavey** [mnylc/islandora_multi_importer#11]
In https://github.com/Islandora/islandora/blob/7.x/islandora.api.php#L749, the second argument to hook_islandora_derivative_alter() is AbstractObject $object. It is a required argument.

In https://github.com/mnylc/islandora_multi_importer/blob/master/includes/mapper.inc#L70, this hook is invoked without supplying an AbstractObject. 

We are seeing an error when we run an ingest because [islandora_checksum_islandora_derivative_alter()](https://github.com/Islandora/islandora_checksum/blob/7.x/islandora_checksum.module#L39) requires this AbstractObject (though it doesn't actually use it).

I don't know if there are any examples of hook_islandora_derivative_alter() out there that require *and actually use* that AbstractObject, but any implementation that does not require it is technically not correct. Likewise, any invocation of this hook also must provide this argument.

I believe the correct solution in this case is to load the cmodel object, and provide that as an argument in the call to drupal_alter().

**Comment by DiegoPino** [comment]
@patdunlavey this is really an Islandora API inconsistency. hook_islandora_derivative(AbstractObject $object = NULL)  accepts NULL for the object itself so should the _alter, but it does not. 
This should be fixed at https://github.com/Islandora/islandora_checksum/blob/7.x/islandora_checksum.module#L39
since both last params should be defaulted to NULL, since they are not required at all.

In the multi importer case the object does not exist yet, since we doing a generic mapping to understand what Datastreams we are able to generate via derivatives and display that to our users. 

I will correct this by passing testing with NULL for both last params, since the CMODEL object is not very useful here anyway, and makes loading slower (we already loaded cmodels in the code). 

But this needs an ticket on islandora checksum and a fix there + in the islandora API

**Comment by DiegoPino** [comment]
Will closed this because even at Core level this was fixed https://github.com/Islandora/islandora/pull/675
