### ISSUE TITLE
PID mapping, PID type, parent type selections have no effect

### ISSUE THREAD

**Issue by patdunlavey** [mnylc/islandora_multi_importer#13]
The functionality implied by these object properties mapping form settings has not been implemented: 

- ['object_maping']['pidmap_row']['pidmap']
- ['object_maping']['pidmap_row']['pidtype']
- ['object_maping']['parentmap_row']['parenttype']

![screen shot 2016-12-02 at 2 21 49 pm](https://cloud.githubusercontent.com/assets/241240/20847153/d98544d0-b89a-11e6-9cb9-358ab072fedd.png)

**Comment by patdunlavey** [comment]
@DiegoPino is this something you have not merged from your development branch?

**Comment by DiegoPino** [comment]
@true, this is not in the main branch. You will see a pull this weekend. Fedora camp is over!

**Comment by patdunlavey** [comment]
Hi @DiegoPino, this issue is a blocker for some work I'm doing right now. It occurs to me that if you want to give me read access to your dev repo, I could fork it, work out the merges and test locally, then issue a PR for this issue.

**Comment by McFateM** [comment]
This issue matches another from my list.  I'd love to have the ability to update an existing object with a new ingest, presumably by including the existing PID in a corresponding call of the CSV.  In the CSV importer that ICG created we allow a field preceded with a hashtag (#) to be treated as a comment so those fields are ignored and not created or updated for an existing object.  Furthermore, I hashtag in the first how long of a role in the CSV indicates that the entire row is to be ignored or treated as a comment. When the CSV importer in just a row it writes the corresponding PID back into the first column of the CSV data, but preceded by a # so that row is effectively ignored in future imports.

**Comment by patdunlavey** [comment]
This issue should be re-tested to see if it is still a problem @McFateM.

**Comment by DiegoPino** [comment]
@patdunlavey seems like I have a pending pull request that I need to rebase :man_facepalming:  . Will be fixed by tonight
Best!

**Comment by DiegoPino** [comment]
@patdunlavey this is fixed. Will close. there are some UX/UI assumptions that we could all talk about, but user provided PIDs are working
