### ISSUE TITLE
Mis-numbered parent row causes infinite loop

### ISSUE THREAD

**Issue by patdunlavey** [mnylc/islandora_multi_importer#14]
I have a csv file that was causing IMI to get stuck in a loop. I eventually figured out that it was because there was a row that had its own row number as the parent ID. Should there be a test around [here](https://github.com/mnylc/islandora_multi_importer/blob/master/includes/islandora_multi_batch.inc#L217) to prevent this? Should it check to see if `$index != $parent` or `$index > $parent`?  Presumably the row should be discarded if so? But what if a subsequent row also has this parent ID, which is for a row that we have now discarded? Is that already handled? Does this need a more careful think?

@DiegoPino

**Comment by DiegoPino** [comment]
@patdunlavey well-known issue and it's not an easy test really, took me a few weeks to solve that. When the infinite loop is a large cyclic pattern, the whole questions is which part of that cycle is wrong? Will submit a fix today. I have a tie-knot-breaker algorithm for that little nasty one on my local machine. Really forgot about this one because @ChrisStanton was bein super careful on not allowing those things to happen, my fault.

Thanks for reporting!

**Comment by patdunlavey** [comment]
Awesome @DiegoPino !

**Comment by DiegoPino** [comment]
@patdunlavey had to finish this on the Train. Well, my Dev approach was too complicated as I stated last night before going to bed, so I went for a simpler one than the one i talked yesterday about.

https://github.com/mnylc/islandora_multi_importer/commit/8ced2a6c87c1912ded7b35f4b34f31fefdf0925c
Also added two `break`statements. Can't really remember why they were not there since the beginning? I hope not for a good reason.

Could you give this a try? With some, for sure, infinite loop and not infinite loop mixed data - csv - excel file?
Much appreciated. If you find trouble (look for those `break`!) please ping me. Amtrak is over 45 minutes of schedule, so have some extra time.

Next step is to inform our users of the PIDs that will eventually created and those that were found wrong. 

Best!
