### ISSUE TITLE
Is there a way to specify the PID?

### ISSUE THREAD

**Issue by kimpham54** [mnylc/islandora_multi_importer#35]
A colleague at UTL is interested in ingesting objects with specific PIDs, in order to immediately relate these items to one another (without using compoundCModel or having to ingest the items first and use the system defined PIDs). 

The idea is that once these objects with specific PIDs are ingested, these PIDs will also used and written into MODS related item of other objects, which they will create a hyperlink to.

I suggested looking at this module, but is it actually possible to specify PIDs using Islandora Multi Importer?

Thanks :)

**Comment by DiegoPino** [comment]
Hi Kim,
Thanks for reminding me of this. I just pulled the code that enables that. https://github.com/mnylc/islandora_multi_importer/commit/0f67e1965cd317e25da84bde2f0ef4dfc168c1ee

The new behavior is:

- If 'Check to let Islandora build PID for you and ignore the Object PID source fields' is disabled you will need to provide a column really and if no value there it will fail. 
- if 'Check to let Islandora build PID for you and ignore the Object PID source fields' is checked, then 'Select the source field to use as Object PID' will be ignored.

Also, it is possible to program some replacement logic if you need that.
Let's say you don´t want to provide a PID but you want to use the PID somewhere.
I could add on the fly a "datainternal.PID" structure that can be used in the Twig engine. In that way, the dynamically PID can be reused when building mods.

I can actually imagine a lot of dynamic data becoming re-injectable into twig template - reusable data. If you or @Natkeeran think this could be useful, feel free to open a ticket.

I will test my own new code this weekend. Also opened a JIRA ticket for the "update part" of IMI. https://jira.duraspace.org/browse/ISLANDORA-2046
This will allow (i have the code written!) to have a single batch queue for updating or creating objects via this.

Good weekend!

**Comment by kimpham54** [comment]
@DiegoPino did you know that you're the absolute best? We will do testing of course as well and get back to you! Enjoy your weekend with puppies!

**Comment by pathintegral** [comment]
Hi Diego,

I checkout to googleAPI-WIP branch to use user defined pid option. However, before the "Process Batch Set" step, my batch contains either 1 or 0 item in it. I tried it on different batches, different twig templates that i used before (which works well with master branch) results are still same.

Waiting for your help, Diego the absolute best!

**Comment by DiegoPino** [comment]
@pathintegral it was fixed via https://github.com/mnylc/islandora_multi_importer/pull/36 (merged). Please give it a test!

**Comment by pathintegral** [comment]
@DiegoPino yeah, i tested and it worked liked a charm!

**Comment by DiegoPino** [comment]
To all in this thread. I added some extra code,[ a little fix ](https://github.com/mnylc/islandora_multi_importer/commit/d63459907226669e90f7a7eb2b72e7f2de023b54 )in case a row containing a PID was invalid some further checks would throw warnings because the ```$objectInfo``` structure would be ```undefined```. Nothing else than a single ```isset```.
Also, side note, probably interesting to you. I added a [re-read button](https://github.com/mnylc/islandora_multi_importer/commit/23dafdc99810ccd1be59bedfcfe7846e6973745d), which means if you need to make a change to your Google Spreadsheet( like renaming a column header, adding columns, etc) that information could be brought back into the multi step setup forms in real time.

Lastly. Not sure if you were aware of this already. Multi importer actually downloads and puts into CSV (to ensure stability and consistency) on ingest (when sending to batch set) data coming from google spreadsheets: So once that is done, any change won´t affect what you already tested as valid. This has an extra interesting consequence. You can then see that file and reuse also  (just press "back to data selection") as a normal upload spreadsheet "ingest" without having to actually upload the file. Can/could be useful.

**Comment by DiegoPino** [comment]
Will close this since it´s done. Thanks to all for this.
